services:
  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    environment:
      - ACCEPT_EULA=Y

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  rmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=application
      - RABBITMQ_DEFAULT_PASS=pepsi

  apiservice:
    image: searchengine
    build:
      context: .
      dockerfile: Apps/SearchEngine/Dockerfile
    ports:
      - 8000:8000
      - 8081:8001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- DOTNET_USE_POLLING_FILE_WATCHER=1 #This is only nesesarry for files
      - ASPNETCORE_URLS=http://+:8000 #Ths allows us to use swagger On the API
      - pgconn=Host=database;Database=UwUgleDB;User Id=postgres;Password=postgres;Port=5432 #Connection string for DB
    depends_on:
      - database
  
  database:
    image: postgres
    ports:
      - "5001:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: UwUgleDB
      #remember to make this environmental secrets /|\
      #secret looks like this:
      #Host=localhost\;Database=UwUgleDB\;User Id=postgres\;Password=postgres\;Port=5001
volumes:
  pgdata: