services:
  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    environment:
      - ACCEPT_EULA=Y

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  rmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=application
      - RABBITMQ_DEFAULT_PASS=pepsi
    healthcheck:
      test:
        rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - apiservice

  apiservice:
    image: searchengine
    build:
      context: .
      dockerfile: Apps/SearchEngine/Dockerfile
    ports:
      - 8000:8000
      - 8081:8001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- DOTNET_USE_POLLING_FILE_WATCHER=1 #This is only nesesarry for files
      - ASPNETCORE_URLS=http://+:8000 #Ths allows us to use swagger On the API
      - pgconn=Host=database;Database=UwUgleDB;User Id=postgres;Password=postgres;Port=5432 #Connection string for DB
    depends_on:
      - database
        
  filecleaner:
    image: filecleaner
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      rmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: Apps/FileCleaner/Dockerfile
    environment:
      - rabbitmq_connection=host=rmq;username=application;password=pepsi;timeout=5;publisherConfirms=true;prefetchcount=50;persistentMessages=true;connectIntervalAttempt=5
  
  fileindexer:
    image: fileindexer
    build:
      context: .
      dockerfile: Apps/FileIndexer/Dockerfile
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      rmq:
        condition: service_healthy
    environment:
      - rabbitmq_connection=host=rmq;username=application;password=pepsi;timeout=5;publisherConfirms=true;prefetchcount=50;persistentMessages=true;connectIntervalAttempt=5
      - pgconn=Host=database;Database=UwUgleDB;User Id=postgres;Password=postgres;Port=5432

  readerservice:
    image: readerservice
    build:
      context: .
      dockerfile: Apps/FileReader/Dockerfile
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1 #This is only nesesarry for files 
      - rabbitmq_connection=host=localhost;username=guest;password=guest;timeout=5;publisherConfirms=true;prefetchcount=50;persistentMessages=true;connectIntervalAttempt=5 #Connectionstring for rabbitmq
      - file_folder=C:\Users\emilw\Downloads\enron_mail_20150507.tar\enron_mail_20150507\maildir
  
  database:
    image: postgres
    command: -c 'max_connections=100'
    ports:
      - "5001:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./SQL:/SQL #Maops sql folder
      - ./scripts/sql-set-up.sh:/docker-entrypoint-initdb.d/sql-set-up.sh #runs initialisation scrips if  database doss sent exist
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: UwUgleDB
      #remember to make this environmental secrets /|\
      #secret looks like this:
      #Host=localhost\;Database=UwUgleDB\;User Id=postgres\;Password=postgres\;Port=5001

volumes:
  pgdata: